name: Build
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
      fail-fast: false
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Create Python venv
        run: |
          python -m venv python/venv
          
      - name: Install Python dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd python
          python -m venv venv
          venv\Scripts\python -m pip install --upgrade pip
          venv\Scripts\pip install faster-whisper
          venv\Scripts\pip install huggingface_hub
          cd ..
          
      - name: Install Python dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          source python/venv/bin/activate
          pip install faster-whisper
          pip install huggingface_hub
          
      - name: Install dependencies
        run: npm install
        
      - name: Build and release Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and release macOS
        if: matrix.os == 'macos-latest'
        run: npm run build:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.zip
            
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/*.dmg
            dist/*.zip
          draft: false
          prerelease: false
          name: Release ${{ github.ref_name }}
          body: |
            Milochy视频文案提取 ${{ github.ref_name }}
            
            ## Windows 用户
            - 下载 zip 文件并解压
            - 运行解压后的 exe 文件
            
            ## Mac 用户
            - 下载 zip 文件并解压
            - 右键点击应用 -> 打开
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 